version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://afrimind:password@db:5432/afrimind
      - REDIS_URL=redis://redis:6379
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - COMMODITY_API_KEY=${COMMODITY_API_KEY}
      - CUSTOMS_API_KEY=${CUSTOMS_API_KEY}
      - SHIPPING_API_KEY=${SHIPPING_API_KEY}
      - LANGUAGE_API_KEY=${LANGUAGE_API_KEY}
      - CULTURAL_DATA_API_KEY=${CULTURAL_DATA_API_KEY}
      - BANKING_API_KEY=${BANKING_API_KEY}
      - MOBILE_MONEY_API_KEY=${MOBILE_MONEY_API_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=afrimind
      - POSTGRES_USER=afrimind
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
